[2024-10-29T22:38:42.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-29T22:38:42.330+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-29T22:38:42.365+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-29T22:38:42.367+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-29T22:38:42.430+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): monetized_stock> on 2024-10-28 22:00:00+00:00
[2024-10-29T22:38:42.444+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-29T22:38:42.451+0000] {standard_task_runner.py:72} INFO - Started process 140 to run task
[2024-10-29T22:38:42.452+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'monetized_stock', 'scheduled__2024-10-28T22:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpv8xumkx1']
[2024-10-29T22:38:42.459+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask monetized_stock
[2024-10-29T22:38:42.615+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [running]> on host 94e12afb2788
[2024-10-29T22:38:42.903+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='monetized_stock' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T22:00:00+00:00'
[2024-10-29T22:38:42.910+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-29T22:38:43.841+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/data_transform.py", line 47, in monetize_stock
    df_stock = pd.read_excel(stock_path, engine='openpyxl')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 582, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 570, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 315, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1446, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")
zipfile.BadZipFile: Bad magic number for central directory
[2024-10-29T22:38:43.881+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=monetized_stock, run_id=scheduled__2024-10-28T22:00:00+00:00, execution_date=20241028T220000, start_date=20241029T223842, end_date=20241029T223843
[2024-10-29T22:38:43.920+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-29T22:38:43.922+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task monetized_stock (Bad magic number for central directory; 140)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/data_transform.py", line 47, in monetize_stock
    df_stock = pd.read_excel(stock_path, engine='openpyxl')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 582, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 570, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 315, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 96, in _validate_archive
    archive = ZipFile(filename, 'r')
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1446, in _RealGetContents
    raise BadZipFile("Bad magic number for central directory")
zipfile.BadZipFile: Bad magic number for central directory
[2024-10-29T22:38:44.011+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-29T22:38:44.069+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-29T22:38:44.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-30T04:03:01.613+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T04:03:01.633+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T04:03:01.642+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T04:03:01.642+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T04:03:01.662+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): monetized_stock> on 2024-10-28 22:00:00+00:00
[2024-10-30T04:03:01.669+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T04:03:01.671+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2024-10-30T04:03:01.671+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'monetized_stock', 'scheduled__2024-10-28T22:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpuwvij7ii']
[2024-10-30T04:03:01.674+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask monetized_stock
[2024-10-30T04:03:01.723+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [running]> on host 7dff020afbaf
[2024-10-30T04:03:01.798+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='monetized_stock' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T22:00:00+00:00'
[2024-10-30T04:03:01.799+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T04:03:02.134+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/data_transform.py", line 47, in monetize_stock
    df_stock = pd.read_excel(stock_path, engine='openpyxl')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 582, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 570, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 317, in load_workbook
    reader.read()
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 276, in read
    self.read_manifest()
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 134, in read_manifest
    src = self.archive.read(ARC_CONTENT_TYPES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1567, in read
    with self.open(name, "r", pwd) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1625, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
[2024-10-30T04:03:02.167+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_update_stock_ferrimac, task_id=monetized_stock, run_id=scheduled__2024-10-28T22:00:00+00:00, execution_date=20241028T220000, start_date=20241030T040301, end_date=20241030T040302
[2024-10-30T04:03:02.181+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T04:03:02.182+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task monetized_stock (Bad magic number for file header; 188)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/functions_etl/data_transform.py", line 47, in monetize_stock
    df_stock = pd.read_excel(stock_path, engine='openpyxl')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 553, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 582, in __init__
    self.book = self.load_workbook(self.handles.handle, engine_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 570, in load_workbook
    return load_workbook(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 317, in load_workbook
    reader.read()
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 276, in read
    self.read_manifest()
  File "/home/airflow/.local/lib/python3.12/site-packages/openpyxl/reader/excel.py", line 134, in read_manifest
    src = self.archive.read(ARC_CONTENT_TYPES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1567, in read
    with self.open(name, "r", pwd) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zipfile/__init__.py", line 1625, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
[2024-10-30T04:03:02.206+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-30T04:03:02.226+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T04:03:02.229+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-30T11:59:19.219+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T11:59:19.293+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T11:59:19.340+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T11:59:19.342+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T11:59:19.413+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): monetized_stock> on 2024-10-28 22:00:00+00:00
[2024-10-30T11:59:19.461+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T11:59:19.484+0000] {standard_task_runner.py:72} INFO - Started process 177 to run task
[2024-10-30T11:59:19.479+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'monetized_stock', 'scheduled__2024-10-28T22:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmp82jts209']
[2024-10-30T11:59:19.502+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask monetized_stock
[2024-10-30T11:59:19.796+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [running]> on host 0d5052666bc5
[2024-10-30T11:59:20.257+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='monetized_stock' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T22:00:00+00:00'
[2024-10-30T11:59:20.261+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T11:59:23.898+0000] {warnings.py:112} WARNING - /opt/***/functions_etl/data_transform.py:52: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_stock.columns = pd.to_datetime(df_stock.columns, errors='ignore', dayfirst=True)

[2024-10-30T11:59:23.942+0000] {warnings.py:112} WARNING - /opt/***/functions_etl/data_transform.py:54: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_list_prices.columns = pd.to_datetime(df_list_prices.columns, errors='ignore', dayfirst=True)

[2024-10-30T11:59:29.282+0000] {data_transform.py:97} INFO - Monetized stock has been successfully updated for date 2024-10-28 00:00:00.
[2024-10-30T11:59:29.287+0000] {python.py:240} INFO - Done. Returned value was:       id_product     model  ... 2024-10-31 00:00:00 2024-11-01 00:00:00
0    ID-00000001     BSX17  ...                 NaN                 NaN
1    ID-00000002      TM12  ...                 NaN                 NaN
2    ID-00000003      TM13  ...                 NaN                 NaN
3    ID-00000004      TM14  ...                 NaN                 NaN
4    ID-00000005      TM15  ...                 NaN                 NaN
..           ...       ...  ...                 ...                 ...
435  ID-00000436  DPS31534  ...                 NaN                 NaN
436  ID-00000437  DPS31535  ...                 NaN                 NaN
437  ID-00000438  DPS31536  ...                 NaN                 NaN
438          NaN       NaN  ...                 NaN                 NaN
439        TOTAL       NaN  ...                 NaN                 NaN

[440 rows x 44 columns]
[2024-10-30T11:59:29.749+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/serialization/serializers/pandas.py:49: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(o)

[2024-10-30T11:59:30.069+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T11:59:30.071+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=monetized_stock, run_id=scheduled__2024-10-28T22:00:00+00:00, execution_date=20241028T220000, start_date=20241030T115919, end_date=20241030T115930
[2024-10-30T11:59:30.379+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T11:59:30.470+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-30T11:59:30.474+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-30T12:49:16.699+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T12:49:16.821+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T12:49:16.884+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T12:49:16.886+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T12:49:16.974+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): monetized_stock> on 2024-10-28 22:00:00+00:00
[2024-10-30T12:49:17.017+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T12:49:17.032+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2024-10-30T12:49:17.032+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'monetized_stock', 'scheduled__2024-10-28T22:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpvk7owrtr']
[2024-10-30T12:49:17.052+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask monetized_stock
[2024-10-30T12:49:17.231+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [running]> on host 1e26175021c2
[2024-10-30T12:49:17.541+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='monetized_stock' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T22:00:00+00:00'
[2024-10-30T12:49:17.544+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T12:49:19.272+0000] {warnings.py:112} WARNING - /opt/***/functions_etl/data_transform.py:52: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_stock.columns = pd.to_datetime(df_stock.columns, errors='ignore', dayfirst=True)

[2024-10-30T12:49:19.287+0000] {warnings.py:112} WARNING - /opt/***/functions_etl/data_transform.py:54: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_list_prices.columns = pd.to_datetime(df_list_prices.columns, errors='ignore', dayfirst=True)

[2024-10-30T12:49:23.480+0000] {data_transform.py:97} INFO - Monetized stock has been successfully updated for date 2024-10-28 00:00:00.
[2024-10-30T12:49:23.482+0000] {python.py:240} INFO - Done. Returned value was:       id_product     model  ... 2024-10-31 00:00:00 2024-11-01 00:00:00
0    ID-00000001     BSX17  ...                 NaN                 NaN
1    ID-00000002      TM12  ...                 NaN                 NaN
2    ID-00000003      TM13  ...                 NaN                 NaN
3    ID-00000004      TM14  ...                 NaN                 NaN
4    ID-00000005      TM15  ...                 NaN                 NaN
..           ...       ...  ...                 ...                 ...
435  ID-00000436  DPS31534  ...                 NaN                 NaN
436  ID-00000437  DPS31535  ...                 NaN                 NaN
437  ID-00000438  DPS31536  ...                 NaN                 NaN
438          NaN       NaN  ...                 NaN                 NaN
439        TOTAL       NaN  ...                 NaN                 NaN

[440 rows x 44 columns]
[2024-10-30T12:49:23.780+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/serialization/serializers/pandas.py:49: UserWarning: The DataFrame has column names of mixed type. They will be converted to strings and not roundtrip correctly.
  table = pa.Table.from_pandas(o)

[2024-10-30T12:49:23.886+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T12:49:23.887+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=monetized_stock, run_id=scheduled__2024-10-28T22:00:00+00:00, execution_date=20241028T220000, start_date=20241030T124916, end_date=20241030T124923
[2024-10-30T12:49:24.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T12:49:24.076+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-30T12:49:24.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-30T16:49:48.389+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T16:49:48.434+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T16:49:48.454+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [queued]>
[2024-10-30T16:49:48.456+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-30T16:49:48.498+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): monetized_stock> on 2024-10-28 22:00:00+00:00
[2024-10-30T16:49:48.512+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=209) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T16:49:48.516+0000] {standard_task_runner.py:72} INFO - Started process 213 to run task
[2024-10-30T16:49:48.517+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_update_stock_ferrimac', 'monetized_stock', 'scheduled__2024-10-28T22:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/object_dag.py', '--cfg-path', '/tmp/tmpb4_qp13l']
[2024-10-30T16:49:48.526+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask monetized_stock
[2024-10-30T16:49:48.644+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_update_stock_ferrimac.monetized_stock scheduled__2024-10-28T22:00:00+00:00 [running]> on host b789ae629a43
[2024-10-30T16:49:48.844+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_update_stock_ferrimac' AIRFLOW_CTX_TASK_ID='monetized_stock' AIRFLOW_CTX_EXECUTION_DATE='2024-10-28T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-28T22:00:00+00:00'
[2024-10-30T16:49:48.846+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T16:49:49.157+0000] {data_transform.py:43} ERROR - One or more files do not exist. Check the names and paths.
[2024-10-30T16:49:49.158+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-30T16:49:49.176+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T16:49:49.178+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_update_stock_ferrimac, task_id=monetized_stock, run_id=scheduled__2024-10-28T22:00:00+00:00, execution_date=20241028T220000, start_date=20241030T164948, end_date=20241030T164949
[2024-10-30T16:49:49.217+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T16:49:49.260+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-30T16:49:49.264+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
